name: ci

on:
  push:
    branches: main

  workflow_dispatch:

env:
  SJASMPLUS_VER: v1.20.1

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: burma5have
          password: ${{ secrets.DOCKERHUB_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: SJASMPLUS_VER=${{ env.SJASMPLUS_VER }}
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: burma5have/sjasmplus:${{ env.SJASMPLUS_VER }},burma5have/sjasmplus:latest

  